// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5jOACVhSwqmdxxmL950MVqG9ZUFeknc',
    appId: '1:815579318707:web:4c96ef7dc0598b811063c6',
    messagingSenderId: '815579318707',
    projectId: 'projeto-g2-67c28',
    authDomain: 'projeto-g2-67c28.firebaseapp.com',
    storageBucket: 'projeto-g2-67c28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5jOACVhSwqmdxxmL950MVqG9ZUFeknc',
    appId: '1:815579318707:android:4c96ef7dc0598b811063c6',
    messagingSenderId: '815579318707',
    projectId: 'projeto-g2-67c28',
    storageBucket: 'projeto-g2-67c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5jOACVhSwqmdxxmL950MVqG9ZUFeknc',
    appId: '1:815579318707:ios:4c96ef7dc0598b811063c6',
    messagingSenderId: '815579318707',
    projectId: 'projeto-g2-67c28',
    storageBucket: 'projeto-g2-67c28.firebasestorage.app',
    iosBundleId: 'com.example.projetoG2',
  );
}